### ISSUE TITLE
Digg Reader não consegue descobrir o feed do blog

### ISSUE THREAD

**Issue by hugollm** [myhro/myhro.github.io#1]
Por algum motivo, o Digg Reader não consegue descobrir o feed, tornando impossível adicionar o blog à lista. No Feedly o discovery funcionou.

Talvez tenha algo errado no formato ou nos cabeçalhos que são servidos no feed. Notei que o arquivo está vindo como "application/xml" por exemplo, uma vez que o correto seria "application/atom+xml" se eu não me engano. Pode ter algo a ver com o formato do xml também.

**Comment by myhro** [comment]
Hugo,

Obrigado por reportar o problema. Já passei por isso com outros feeds, visto que sou usuário do Digg Reader, mas não havia me dado conta que o mesmo não funciona com o meu próprio blog. :-)

A suspeita que tenho é que o Digg Reader não suporte qualquer feed que seja adicionado, talvez só de sites que ele "conheça" de uma forma ou de outra. Procurei no [FAQ](https://digg.zendesk.com/categories/20065355-FAQs), na seção [Feeds and Folders](https://digg.zendesk.com/forums/20809775-Feeds-and-Folders), e não encontrei nada relacionado. Há uma pergunta bem específica, ["How to create a Digg Reader link for my website"](https://digg.zendesk.com/entries/22753409-How-to-create-a-Digg-Reader-link-for-my-website), mas além de não ter nenhuma resposta concreta, o tópico inteiro parece infestado por SPAM.

Acredito que a solução mais simples seja usar uma ponte, como o [FeedBurner](https://en.wikipedia.org/wiki/FeedBurner): http://feeds.feedburner.com/MyhroBlog

Estranhamente, se você usar `https://` o Digg Reader não identifica corretamente o feed... Vai entender.

Atualizei o rodapé do site para incluir a nova URL do RSS e me inscrevi nele no Digg Reader, de forma que perceberei caso o mesmo pare de funcionar novamente.

Abraços.

**Comment by hugollm** [comment]
Show! Não entendi essa do `https`, será que é isso mesmo? Imagino que o formato do seu feed é aquele padrão do jekyll né? Bom, de qualquer forma o FeedBurner resolvou o problema direitinho. O discovery funciona agora até na url principal. Valeu, jovem!

**Comment by myhro** [comment]
Hugo,

> Imagino que o formato do seu feed é aquele padrão do jekyll né?

Sim, não modifiquei a geração do feed.

> Bom, de qualquer forma o FeedBurner resolvou o problema direitinho. O discovery funciona agora até na url principal.

Excelente constatação. Foram dois coelhos então. :-)

> Valeu, jovem!

Eu quem agradeço. Muito obrigado!

Abraços.
